apiVersion: v1
data:
  autoexec.cfg: |
    hostname "alvin csgo server"
    sv_cheats 0 //This should always be set, so you know it's not on
    sv_lan 0 //This should always be set, so you know it's not on
    sv_password "indecision"
    rcon_password "adminpass"
    sv_allowdownload 1
    sv_consistency 1
    sv_contact 0
    sv_allowupload 1
    sv_downloadurl ""
    mp_forcecamera 0
    exec banned_user.cfg
    exec banned_ip.cfg
  gamemodes.txt: ""
  gamemodes_server.txt: ""
  server.cfg: |
    bot_quota 1
    bot_quota_mode competitive
    mp_buytime 9999
    mp_buy_anywhere 0
    mp_buy_during_immunity 0
    mp_free_armor 1
    mp_halftime 1
    mp_match_can_clinch 1
    mp_autoteambalance 0
    mp_limitteams 0
    mp_freezetime 0
    mp_autokick 0
    mp_round_restart_delay 3.0
    mp_friendlyfire 1
    mp_win_panel_display_time 3
    mp_ggprogressive_round_restart_delay 15
    mp_ggtr_bomb_defuse_bonus 1
    mp_ggtr_bomb_detonation_bonus 1
    mp_ggtr_bomb_pts_for_flash 4
    mp_ggtr_bomb_pts_for_he 3
    mp_ggtr_bomb_pts_for_molotov 5
    mp_ggtr_bomb_pts_for_upgrade 2
    mp_ggtr_bomb_respawn_delay 0
    mp_ggtr_end_round_kill_bonus 1
    mp_ggtr_halftime_delay 0.0
    mp_ggtr_last_weapon_kill_ends_half 0
    mp_respawn_immunitytime 1
    mp_weapons_allow_typecount -1
    mp_molotovusedelay 0
    ammo_grenade_limit_default 99999
    ammo_grenade_limit_flashbang 99999
    ammo_grenade_limit_total 99999
    mp_halftime_duration 5
    mp_maxmoney 16000
    mp_maxrounds 30
    mp_roundtime 1.92
    mp_roundtime_hostage 1.92
    mp_roundtime_defuse 1.92
    mp_solid_teammates 1
    mp_startmoney 16000
    mp_timelimit 0
    mp_warmuptime 300
    sv_allow_votes 0
    sv_auto_full_alltalk_during_warmup_half_end 1
    mp_warmup_pausetimer 0
    mp_halftime_pausetimer 0
    mp_randomspawn 0
    mp_randomspawn_los 0
    sv_infinite_ammo 0
    mp_weapons_allow_map_placed 1
    mp_respawn_on_death_t 0
    mp_respawn_on_death_ct 0
    mp_ct_default_primary weapon_ak47
    mp_t_default_primary weapon_ak47
    mp_default_team_winner_no_objective -1
    ff_damage_reduction_bullets 0.33
    ff_damage_reduction_grenade 0.85
    ff_damage_reduction_grenade_self 1
    ff_damage_reduction_other 0.4
    mp_afterroundmoney 16000
    spec_freeze_panel_extended_time 0
    spec_freeze_time 2.0
    mp_display_kill_assists 1
    sv_occlude_players 1
    occlusion_test_async 0
    spec_replay_enable 0
    writeid
    writeip

    say "------config loaded v2------"
kind: ConfigMap
metadata:
  name: csgo-configuration
  namespace: csgo-server