apiVersion: v1
data:
  autoexec.cfg: |
    hostname "alvin csgo server"
    sv_cheats 0 //This should always be set, so you know it's not on
    sv_lan 0 //This should always be set, so you know it's not on
    exec banned_user.cfg
    exec banned_ip.cfg
  gamemodes.txt: ""
  gamemodes_server.txt: ""
  server.cfg: |
    mp_autoteambalance 0
    mp_limitteams 0
    mp_freezetime 0
    mp_autokick 0
    mp_round_restart_delay 5.0
    mp_halftime_duration 5
    sv_allowdownload 1
    sv_consistency 0
    sv_contact 0
    sv_allowupload 1
    sv_downloadurl ""
    sv_lan 0
    sv_hibernate_when_empty 0
    sv_log_onefile 0
    sv_logecho 1
    sv_logfile 1
    sv_logsdir logfiles
    sv_pure 0
    sv_pure_kick_clients 0
    sv_password "indecision"
    writeid
    writeip

    say "------config loaded------"
kind: ConfigMap
metadata:
  name: csgo-configuration
  namespace: csgo-server